replicaCount: 1




image:
  # repository will be built by your Makefile/Dockerfile
  repository: "market-data-api"
  tag: "local"
  pullPolicy: IfNotPresent

service:
  targetPort: http
  httpPort: 8000

probes:
  readiness:
    initialDelaySeconds: 15
    periodSeconds: 5
  liveness:
    initialDelaySeconds: 15
    periodSeconds: 20

env:
  SERVICE_NAME: "market-data-api"
  SERVICE_DESC: "A stateless micro‑service delivering your dreams."
  API_VER: "0.1.0"
  PORT: 8000
  ENVIRONMENT: development

