version: "3.8"

services:
  
  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  

  

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME:-market-data-api}
    depends_on:
      - redis
      
    ports:
      - "${APP_PORT:-8000}:8000"
    environment:
      
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT:-6379}
      
      
    command: >
      uvicorn src.app.main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  kafka_data:
