
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    { { - include "chart.labels" . | nindent 4 } }
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      { { - include "chart.labels" . | nindent 4 } }
  template:
    metadata:
      labels:
        { { - include "chart.labels" . | nindent 4 } }
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort }}

          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: "{{ $val }}"
            {{- end }}

          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.httpPort }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}

          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.httpPort }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}

