{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-redis
  labels:
    app: {{ include "chart.fullname" . }}-redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app: {{ include "chart.fullname" . }}-redis
{{- end }}
